package cup;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PONTOVIRGULA = 47;
  public static final int DIVISOR = 38;
  public static final int SHORT = 12;
  public static final int MULTIPLICADORIGUAL = 30;
  public static final int SCANF = 19;
  public static final int CONST = 5;
  public static final int CHAR = 7;
  public static final int DIFERENTE = 28;
  public static final int DOUBLE = 9;
  public static final int LPAREN = 41;
  public static final int INT = 13;
  public static final int MAISIGUAL = 33;
  public static final int MAIORIGUAL = 27;
  public static final int FOR = 51;
  public static final int PONTO = 50;
  public static final int VIRGULA = 48;
  public static final int RPAREN = 42;
  public static final int STATIC = 3;
  public static final int DEFINE = 53;
  public static final int AND = 39;
  public static final int MENORIGUAL = 26;
  public static final int IGUAL = 29;
  public static final int OR = 40;
  public static final int MAIS = 35;
  public static final int NUM = 54;
  public static final int EXTERN = 4;
  public static final int IF = 15;
  public static final int ID = 57;
  public static final int MULTIPLICADOR = 37;
  public static final int CRLF = 56;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int MAIOR = 23;
  public static final int error = 1;
  public static final int MENOS = 36;
  public static final int MENOR = 24;
  public static final int UNSIGNED = 11;
  public static final int AUTO = 2;
  public static final int BREAK = 20;
  public static final int VOID = 6;
  public static final int MODIGUAL = 32;
  public static final int PRINTF = 18;
  public static final int LBRACK = 45;
  public static final int LITERAL = 55;
  public static final int LBRACE = 43;
  public static final int ELSE = 16;
  public static final int RBRACK = 46;
  public static final int SIGNED = 10;
  public static final int ENUM = 22;
  public static final int IGUALIGUAL = 25;
  public static final int WHILE = 52;
  public static final int DIVISORIGUAL = 31;
  public static final int FLOAT = 8;
  public static final int RBRACE = 44;
  public static final int MENOSIGUAL = 34;
  public static final int LONG = 14;
  public static final int STRUCT = 21;
  public static final int ASPAS = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AUTO",
  "STATIC",
  "EXTERN",
  "CONST",
  "VOID",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "SIGNED",
  "UNSIGNED",
  "SHORT",
  "INT",
  "LONG",
  "IF",
  "ELSE",
  "RETURN",
  "PRINTF",
  "SCANF",
  "BREAK",
  "STRUCT",
  "ENUM",
  "MAIOR",
  "MENOR",
  "IGUALIGUAL",
  "MENORIGUAL",
  "MAIORIGUAL",
  "DIFERENTE",
  "IGUAL",
  "MULTIPLICADORIGUAL",
  "DIVISORIGUAL",
  "MODIGUAL",
  "MAISIGUAL",
  "MENOSIGUAL",
  "MAIS",
  "MENOS",
  "MULTIPLICADOR",
  "DIVISOR",
  "AND",
  "OR",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "PONTOVIRGULA",
  "VIRGULA",
  "ASPAS",
  "PONTO",
  "FOR",
  "WHILE",
  "DEFINE",
  "NUM",
  "LITERAL",
  "CRLF",
  "ID"
  };
}

